const DATA={
    collection:[
        {
            id:1,
            title:"Dry fruits",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323493/Nuts_h2bjzr.jpg"
,
        },
        {
            id:2,
            title:"Vegetables",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323529/Carrot_zomham.jpg"

,
        }
        ,
        {
            id:3,
            title:"Fruits",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323815/Pomegranate_gv5mtv.jpg"
        },
        {
            id:4,
            title:"Juices",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323815/Pomegranate_gv5mtv.jpg"
        },
        {
            id:5,
            title:"dairy'",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745324727/freepik__upload__80104_noubkg.jpg",
        },
        {
            id:6,
            title:"non-veg",
            img:"https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323394/Egg_almuqv.jpg",
        }
    ],

    cart:[
        {
            id:1,
            title:"Apple",
            price:100,
            img:'',
            category:'fruit',
            quantity:1
        },
        {
            id:2,
            title:"Banana",
            price:200,
            img:'',
            category:'fruit',
            quantity:1
        },
        {
            id:3,
            title:"Orange",
            price:300,
            img:'',
            category:'fruit',
            quantity:1
        },
        {
            id:4,
            title:"kiwi",
            price:300,
            img:'',
            category:'fruit',
            quantity:1
        },
        {
            id:5,
            title:"mangoe",
            price:300,
            img:'',
            category:'fruit',
            quantity:1
        }
        ,
        {
            id:6,
            title:"grapes",
            price:300,
            img:'',
            category:'fruit',
            quantity:1
        },
        {
            id:7,
            title:"broccoli",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        },
        {
            id:8,
            title:"carrot",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        }
        ,
        {
            id:9,
            title:"beetroot",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        }
        ,
        {
            id:10,
            title:"green beans",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        }
        ,
        {
            id:11,
            title:"spinach",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        },
        {
            id:12,
            title:"cabbage",
            price:300,
            img:'',
            category:'vegetables',
            quantity:1
        },
        {
            id:13,
            title:"cashew nuts",
            price:300,
            img:'',
            category:'dryFruits',
            quantity:1
        },
        {
            id:14,
            title:"almonds",
            price:300,
            img:'',
            category:'dryFruits',
            quantity:1
        },
        {
            id:15,
            title:"walnuts",
            price:300,
            img:'',
            category:'dryFruits',
            quantity:1
        },
        {
            id:16,
            title:"pistachio",
            price:300,
            img:'',
            category:'dryFruits',
            quantity:1
        },
        {
            id:17,
            title:"raisins",
            price:300,
            img:'',
            category:'dryFruits',
            quantity:1
        },
        {
            id:18,
            title:"Milk",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:19,
            title:"Cheese",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:20,
            title:"Curd",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:21,
            title:"cottage cheese",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:22,
            title:"butter milk",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:23,
            title:"clarifed butter",
            price:300,
            img:'',
            category:'dairy',
            quantity:1
        },
        {
            id:24,
            title:"chicken",
            price:300,
            img:'',
            category:'nonVeg',
            quantity:1
        },
        {
            id:25,
            title:"mutton",
            price:300,
            img:'',
            category:'nonVeg',
            quantity:1
        },
        {
            id:26,
            title:"Fish",
            price:300,
            img:'',
            category:'nonVeg',
            quantity:1
        },
        {
            id:27,
            title:"prawns",
            price:300,
            img:'',
            category:'nonVeg',
            quantity:1
        },
        {
            id:28,
            title:"eggs",
            price:300,
            img:'',
            category:'nonVeg',
            quantity:1
        }
    ],
    product:[
        {
            id:1,
            title:"Apple",
            price:100,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745325293/11473559_kqimck.png',
            category:'fruit',
            quantity:1
        },
        {
            id:2,
            title:"pomogranate",
            price:200,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323815/Pomegranate_gv5mtv.jpg',
            category:'fruit',
            quantity:1
        },
        {
            id:3,
            title:"banana",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745325378/freepik__upload__61997_aes1tj.jpg',
            category:'fruit',
            quantity:1
        },
        
        {
            id:4,
            title:"mangoe",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745325696/yellow-mango-1000x1000_w0mrqp.webp',
            category:'fruit',
            quantity:1
        },
        {
            id:5,
            title:"cabbage",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745078300/c62nh0rsnkmdwanyrwst.jpg',
            category:'vegetables',
            quantity:1
        },
        {
            id:6,
            title:"broccoli",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745078300/egh8bnxhyegfhsa7jgaz.jpg',
            category:'vegetables',
            quantity:1
        },
        {
            id:7,
            title:"carrot",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323529/Carrot_zomham.jpg',
            category:'vegetables',
            quantity:1
        },
        {
            id:8,
            title:"bitter gourd",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745078299/ucqk3b7iiy3sibhye4vu.jpg',
            category:'vegetables',
            quantity:1
        },
        {
            id:9,
            title:"capsicum",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745078299/pvslzysgaq2phfuzozwv.jpg',
            category:'vegetables',
            quantity:1
        },
        {
            id:10,
            title:"cashew nuts",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745326328/cashewnut2_gozoti.webp',
            category:'dryFruits',
            quantity:1
        },
        {
            id:11,
            title:"almonds",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745326477/Almond_e29eo4.webp',
            category:'dryFruits',
            quantity:1
        },
        
        {
            id:13,
            title:"pistachio",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745323493/Nuts_h2bjzr.jpg',
            category:'dryFruits',
            quantity:1
        },
        {
            id:14,
            title:"raisins",
            price:300,
            img:'https://res.cloudinary.com/dpfspbjyk/image/upload/v1745326353/raisins1_1_gw6zrb.jpg',
            category:'dryFruits',
            quantity:1
        },
    ]

}

export default DATA;
// export the DATA object so it can be imported in other files